apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webserver
  name: nginx-deployment-web
  labels:
    app: nginx_haproxy
    important: "true"
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx_haproxy
  template:
    metadata:
      labels: 
        app: nginx_haproxy
    spec: 
      containers:
        - image: busy-box
          name: nginx-depoloyment
          #command: ["/bin/sh", "-c", "while true; do wget -q -O- http://nginx-service; done && sleep 3600"]
          ports: 
            - containerPort: 8080
          resources:
            limits: 
              memory: 512Mi
              cpu: 128m
            requests:
              memory: 512Mi
              cpu: 128m
          env:
            - name: HOLE
              value: "Im fine! thanks!"

