apiVersion: v1
kind: Namespace
metadata: 
  name: webserver
---
apiVersion: v1
kind: Pod
metadata:
  namespace: webserver
  name: nginx
  labels:
    app: backend
    important: "true"
spec:
  containers:
    - image: nginx:latest
      name: web-nginx
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: 512Mi
          cpu: 256m
        requests:
          memory: 512Mi
          cpu: 256m
      env:
        - name: HELLO
          value: "Hello World"