apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: webserver
  name: nginx-replicaset
  labels:
    app: nginx-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      key: nginx-replicaset
  template:
    metadata:
      labels:
        key: nginx-replicaset
    spec:
      containers:
          - image: busy-box:latest
            name: my-nginx
            ports:
              - containerPort: 8080
            resources:
              limits:
                memory: 512Mi
                cpu: 256m
              requests:
                memory: 512Mi
                cpu: 256m
            env:
              - name: HELLONGINX
                value: "Hello World NGINX"
