services:
  webservice:
    image: nginx:latest
    container_name: nginx-webservice
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app-backend
    networks:
      - app-network

  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    volumes:
      - ./backend:/var/www/html/backend
    depends_on:
      - database
      - redis
    networks:
      - app-network

  app-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/html/frontend
    networks:
      - app-network

  database:
    image: mysql:latest
    container_name: mysql-database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  db-data: